### ISSUE TITLE
分享的图片大小限制

### ISSUE THREAD

**Issue by XingAndroid** [devzwy/SocialHelper#1]
你们做的图片大小限制了吗，微信分享图片，小程序  缩略图的等等

**Comment by devzwy** [comment]
缩略图内部都是有自己做处理的，会被等比例缩放到150*150；不知道你问的是什么意思。
可以参考[微信分享](https://github.com/devzwy/SocialHelper/blob/main/WeChat/src/main/java/io/github/devzwy/socialhelper/wechat/WeChatSocialHelperExt.kt)查看源码。
